<?php

namespace Samane\Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promoteur extends \Promoteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Promoteur' . "\0" . 'idPromoteur', '' . "\0" . 'Promoteur' . "\0" . 'personne', '' . "\0" . 'Promoteur' . "\0" . 'nomStructure', '' . "\0" . 'Promoteur' . "\0" . 'combats', '' . "\0" . 'Promoteur' . "\0" . 'tournoiLuttes'];
        }

        return ['__isInitialized__', '' . "\0" . 'Promoteur' . "\0" . 'idPromoteur', '' . "\0" . 'Promoteur' . "\0" . 'personne', '' . "\0" . 'Promoteur' . "\0" . 'nomStructure', '' . "\0" . 'Promoteur' . "\0" . 'combats', '' . "\0" . 'Promoteur' . "\0" . 'tournoiLuttes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Promoteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPromoteur()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPromoteur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPromoteur', []);

        return parent::getIdPromoteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPromoteur($idPromoteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPromoteur', [$idPromoteur]);

        return parent::setIdPromoteur($idPromoteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonne', []);

        return parent::getPersonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonne($personne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonne', [$personne]);

        return parent::setPersonne($personne);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomStructure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomStructure', []);

        return parent::getNomStructure();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomStructure($nomStructure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomStructure', [$nomStructure]);

        return parent::setNomStructure($nomStructure);
    }

    /**
     * {@inheritDoc}
     */
    public function getCombats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCombats', []);

        return parent::getCombats();
    }

    /**
     * {@inheritDoc}
     */
    public function setCombats($combats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCombats', [$combats]);

        return parent::setCombats($combats);
    }

    /**
     * {@inheritDoc}
     */
    public function getTournoiLuttes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTournoiLuttes', []);

        return parent::getTournoiLuttes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTournoiLuttes($tournoiLuttes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTournoiLuttes', [$tournoiLuttes]);

        return parent::setTournoiLuttes($tournoiLuttes);
    }

}
